version: "3.8"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - static-volume:/usr/src/app/.next
    nginx:
        restart: always
        depends_on:
            - app
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        volumes: 
            - static-volume:/var/www/_next
        ports:
            - "8080:8080"
volumes: 
    static-volume: