version: "3.8"
services:
    app-client:
        build:
            context: ./
            dockerfile: Dockerfile.app-client
        volumes: 
            - static-volume:/usr/src/app/apps/client/.next
    app-client-nginx:
        restart: always
        depends_on:
            - app-client
        build:
            context: ./
            dockerfile: Dockerfile.app-client-nginx
        volumes: 
            - static-volume:/var/www/_next
        ports:
            - "8080:8080"
volumes: 
    static-volume: