FROM node:16-alpine

# Create temp to build the project
WORKDIR /usr/src/app

COPY . .

RUN yarn install
RUN yarn workspace @app/client build

EXPOSE 3000
CMD [ "yarn", "workspace", "@app/client", "start" ]